# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:          pretty
# Setup
title:               Opinioni
tagline:             'di Andrea Marcacci'
description:         "Questo sito è un'occasione di poter esprimere opinioni e pensieri. Ogni testo qui riprodotto rappresenta un pesniero passatomi per la testa. Vi prego di non interpretare i miei post come un attacco, personale o no, ma piuttosto come uno spunto di riflessione."
url:                 http://lanyon.getpoole.com
baseurl:             ''
plugins:              [jekyll-paginate]
gems:                  [jekyll-paginate]
paginate:             1
paginate_path:       "page:num"

# About/contact
author:
  name:              Andrea Marcacci
  url:               https://twitter.com/cosedimarca
  email:             andrea.marcacci@gmail.com

# Custom vars
version:             0.0.1
